version: "3"
services:
  server:
    container_name: server
    build: ./server
    ports:
      - 8000:8000
    links:
      - mongo
    environment:
      - NODE_ENV=production

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017

  web:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    links:
      - server
